Question 1 = Extracting Tesla Stock Data Using yfinance

In [97]:
import yfinance as yf
import pandas as pd
import requests
from bs4 import BeautifulSoup
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [98]:
tesla = yf.Ticker("TSLA")

In [99]:
tesla_data = tesla.history(period="max")
tesla_data.reset_index(inplace=True)

In [100]:
tesla_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2010-06-29 00:00:00-04:00,1.266667,1.666667,1.169333,1.592667,281494500,0.0,0.0
1,2010-06-30 00:00:00-04:00,1.719333,2.028000,1.553333,1.588667,257806500,0.0,0.0
2,2010-07-01 00:00:00-04:00,1.666667,1.728000,1.351333,1.464000,123282000,0.0,0.0
3,2010-07-02 00:00:00-04:00,1.533333,1.540000,1.247333,1.280000,77097000,0.0,0.0
4,2010-07-06 00:00:00-04:00,1.333333,1.333333,1.055333,1.074000,103003500,0.0,0.0

Question 2 = Extracting Tesla Revenue Data Using Webscraping

In [101]:
url = 'https://companiesmarketcap.com/tesla/revenue/'
data = requests.get(url).text
soup = BeautifulSoup(data, 'html.parser')

revenue_data = pd.DataFrame(columns=["Years", "Revenue"])

for row in soup.find('table').find_all('tr'):
    cols = row.find_all('td')
    if len(cols) >= 2:  # Check if there are at least 2 columns (year and revenue)
        year = cols[0].text
        revenue = cols[1].text
        revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)


print(revenue_df)

         Years   Revenue
0   2023 (TTM)  $94.02 B
1         2022  $81.46 B
2         2021  $53.82 B
3         2020  $31.53 B
4         2019  $24.57 B
5         2018  $21.46 B
6         2017  $11.75 B
7         2016   $7.00 B
8         2015   $4.04 B
9         2014   $3.19 B
10        2013   $2.01 B
11        2012   $0.41 B
12        2011   $0.20 B
13        2010   $0.11 B
14        2009   $0.11 B

<ipython-input-101-209b02de595e>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-101-209b02de595e>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-101-209b02de595e>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-101-209b02de595e>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-101-209b02de595e>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-101-209b02de595e>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-101-209b02de595e>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-101-209b02de595e>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-101-209b02de595e>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-101-209b02de595e>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-101-209b02de595e>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-101-209b02de595e>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-101-209b02de595e>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-101-209b02de595e>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-101-209b02de595e>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)

Question 3 -
Extracting GameStop Stock Data Using yfinance

In [102]:
gamerstock = yf.Ticker("GME")
gme_history = gamerstock.history(period="max")
gme_history.reset_index(inplace=True)
gme_history.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2002-02-13 00:00:00-05:00,1.620128,1.693349,1.603295,1.691666,76216000,0.0,0.0
1,2002-02-14 00:00:00-05:00,1.712707,1.716074,1.670626,1.683250,11021600,0.0,0.0
2,2002-02-15 00:00:00-05:00,1.683251,1.687459,1.658002,1.674834,8389600,0.0,0.0
3,2002-02-19 00:00:00-05:00,1.666418,1.666418,1.578047,1.607504,7410400,0.0,0.0
4,2002-02-20 00:00:00-05:00,1.615921,1.662210,1.603296,1.662210,6892800,0.0,0.0

Question 4 -  Extracting GameStop Revenue Data Using Webscraping - 1 Points

In [109]:
url = 'https://companiesmarketcap.com/gamestop/revenue/'
data = requests.get(url).text
soup = BeautifulSoup(data, 'html.parser')

revenue_df = pd.DataFrame(columns=["Years", "Revenue"])

for row in soup.find('table').find_all('tr'):
    cols = row.find_all('td')
    if len(cols) >= 2:  # Check if there are at least 2 columns (year and revenue)
        year = cols[0].text
        revenue = cols[1].text
        revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)


print(revenue_df)

         Years  Revenue
0   2023 (TTM)  $5.78 B
1         2022  $5.95 B
2         2021  $5.87 B
3         2020  $5.16 B
4         2019  $7.33 B
5         2018  $9.16 B
6         2017  $8.76 B
7         2016  $9.08 B
8         2015  $9.31 B
9         2014  $9.50 B
10        2013  $8.91 B
11        2012  $8.90 B
12        2011  $9.66 B
13        2010  $9.30 B
14        2009  $9.04 B
15        2008  $8.17 B
16        2007  $6.53 B
17        2006  $4.68 B
18        2005  $2.13 B
19        2004  $1.75 B
20        2003  $1.47 B
21        2002  $1.34 B

<ipython-input-109-f18cded926c8>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-109-f18cded926c8>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-109-f18cded926c8>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-109-f18cded926c8>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-109-f18cded926c8>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-109-f18cded926c8>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-109-f18cded926c8>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-109-f18cded926c8>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-109-f18cded926c8>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-109-f18cded926c8>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-109-f18cded926c8>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-109-f18cded926c8>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-109-f18cded926c8>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-109-f18cded926c8>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-109-f18cded926c8>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-109-f18cded926c8>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-109-f18cded926c8>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-109-f18cded926c8>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-109-f18cded926c8>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-109-f18cded926c8>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-109-f18cded926c8>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)
<ipython-input-109-f18cded926c8>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  revenue_df = revenue_df.append({'Years': year, 'Revenue': revenue}, ignore_index=True)

Question 5 - Tesla Stock and Revenue Dashboard - 2 Points

In [107]:
def make_graph(tesla_data, revenue_data, TSLA):
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, subplot_titles=("Historical Share Price", "Historical Revenue"), vertical_spacing = .3)
    stock_data_specific = tesla_data[tesla_data.Date <= '2021-06-14']
    revenue_data_specific = revenue_data[revenue_data.Date <= '2021-04-30']
    fig.add_trace(go.Scatter(x=pd.to_datetime(stock_data_specific.Date, infer_datetime_format=True), y=stock_data_specific.Close.astype("float"), name="Share Price"), row=1, col=1)
    fig.add_trace(go.Scatter(x=pd.to_datetime(revenue_data_specific.Date, infer_datetime_format=True), y=revenue_data_specific.Revenue.astype("float"), name="Revenue"), row=2, col=1)
    fig.update_xaxes(title_text="Date", row=1, col=1)
    fig.update_xaxes(title_text="Date", row=2, col=1)
    fig.update_yaxes(title_text="Price ($US)", row=1, col=1)
    fig.update_yaxes(title_text="Revenue ($US Millions)", row=2, col=1)
    fig.update_layout(showlegend=False,
    height=900,
    title=TSLA,
    xaxis_rangeslider_visible=True)
    fig.show()

Question 6 - GameStop Stock and Revenue Dashboard- 2 Points

In [106]:
def make_graph(gme_history, revenue_df2, GME):
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, subplot_titles=("Historical Share Price", "Historical Revenue"), vertical_spacing = .3)
    stock_data_specific = gme_history[gme_history.Date <= '2021-06-14']

    revenue_data_specific = revenue_data[revenue_data.Date <= '2021-04-30']
    fig.add_trace(go.Scatter(x=pd.to_datetime(stock_data_specific.Date, infer_datetime_format=True), y=stock_data_specific.Close.astype("float"), name="Share Price"), row=1, col=1)
    fig.add_trace(go.Scatter(x=pd.to_datetime(revenue_data_specific.Date, infer_datetime_format=True), y=revenue_data_specific.Revenue.astype("float"), name="Revenue"), row=2, col=1)
    fig.update_xaxes(title_text="Date", row=1, col=1)
    fig.update_xaxes(title_text="Date", row=2, col=1)
    fig.update_yaxes(title_text="Price ($US)", row=1, col=1)
    fig.update_yaxes(title_text="Revenue ($US Millions)", row=2, col=1)
    fig.update_layout(showlegend=False,
    height=900,
    title=GME,
    xaxis_rangeslider_visible=True)
    fig.show()

Question 7 - Sharing your Assignment Notebook - 2 Points